spring.application.name=crudpeliculasmysql

spring.datasource.url=jdbc:mysql://localhost:3306/xideral
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
