spring.application.name=webflux-flux
server.port=8075

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%15.15t]){magenta} %clr(%-40.40logger{39}){cyan} : %msg%n
logging.level.com.academymty=INFO
