spring.application.name=crudpeliculasmongo

spring.mongodb.uri=mongodb://localhost:27017/xideral
#spring.mongodb.uri=mongodb+srv://root:admin@cluster0.sqekt1u.mongodb.net/xideral?appName=Cluster0

server.port=8081